HEADER_COMMON_INFO = '** US DOLLARS **'
TABLE_HEADER_CONFIRMATION = 'TRADE SETTL AT BUY SELL CONTRACT DESCRIPTION EX PRICE CC DEBIT/CREDIT'
TABLE_HEADER_JOURNAL = 'TRADE SETTL AT LONG SHORT JOURNAL DESCRIPTION EX TRADE PRICE CC DEBIT/CREDIT'
TABLE_HEADER_OPEN_POSITIONS = 'TRADE CARD AT LONG SHORT CONTRACT DESCRIPTION EX PRICE CC DEBIT/CREDIT'
TABLE_HEADER_PURCHASE_AND_SALE = 'TRADE SETTL AT LONG SHORT CONTRACT DESCRIPTION EX PRICE CC DEBIT/CREDIT'

JOURNAL_ACTIONS = {
  'DATA FEE' => :ActionKind_MarketDataFee,
  'WT CREDIT' => :ActionKind_Deposit,
  'WT DEBIT' => :ActionKind_Withdrawal,
  'WT FEE' => :ActionKind_WithdrawalFee
}

FILE_NAME_REPORT = "Report.xlsx"
FILE_NAME_USD_RATES = "USDRates.txt"

MONTH_SHORTS = %w[JAN FEB MAR APR MAY JUN JUL AUG SEP OCT NOV DEC]
FORMALIZED_INSTRUMENT = /\A(#{MONTH_SHORTS.join('|')}) \d\d /
